name: Build Makaroni
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - name: Build Uber JAR
      run: ./gradlew shadowJar
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Makaroni
        path: './build/libs/Makaroni-2.0-SNAPSHOT-all.jar'
